version: '3.8'

services:
  reddit-mcp-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SYSTEMPROMPT_API_KEY=${SYSTEMPROMPT_API_KEY}
      - OAUTH_ISSUER=${OAUTH_ISSUER:-https://server.smithery.ai/@Ejb503/systemprompt-reddit-mcp}
      - PORT=${PORT:-3000}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped