# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json tsconfig.test.json ./
COPY src ./src
COPY config ./config
COPY ARCHITECTURE.md TEMPLATE_GUIDE.md README.md LICENSE.md ./

RUN npm ci --ignore-scripts && npm run build

# Production environment
ENV NODE_ENV=production

ENTRYPOINT ["node", "build/index.js"]
