version: '3.8'

services:
  reddit-mcp-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_REDIRECT_URI=${REDDIT_REDIRECT_URI:-http://172.31.174.192:3000/oauth/reddit/callback}
      - SYSTEMPROMPT_API_KEY=${SYSTEMPROMPT_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - OAUTH_ISSUER=${OAUTH_ISSUER:-http://172.31.174.192:3000}
      - PORT=${PORT:-3000}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped